### ISSUE TITLE
Before rollback is not executed in some cases

### ISSUE THREAD

**Issue by amishyn** [aaronmallen/activeinteractor#228]
#### Current Behavior

Before rollback is not executed on previously successful interactors.

```
2.6.5 :130 > MyOrganizer.perform
perform 1
perform 2 fail
before rollback 2
rollback 2
rollback 1
```

#### Expected Behavior
```
2.6.5 :130 > MyOrganizer.perform
perform 1
perform 2 fail
before rollback 2
rollback 2
**before rollback 1**
rollback 1
```
#### Steps to Reproduce

```
class MyInteractor1 < ActiveInteractor::Base
  before_rollback  { puts 'before rollback 1' }
  def perform
    puts 'perform 1'
  end

  def rollback
    puts 'rollback 1'
  end
end
class MyInteractor2 < ActiveInteractor::Base
  before_rollback  { puts 'before rollback 2' }
  def perform
    puts 'perform 2 fail'
    context.fail!
  end

  def rollback
    puts 'rollback 2'
  end
end
class MyOrganizer < ActiveInteractor::Organizer::Base
  organize :my_interactor_1, :my_interactor_2
end
```

**Comment by mohameddiaa27** [comment]
I think the problem happens because upon rollback trigger, we actually run rollback callbacks but only for the current interactor:

https://github.com/aaronmallen/activeinteractor/blob/1f4afa8b7cc8fcfd890ef555622f6f2274eaa632/lib/active_interactor/interactor/worker.rb#L84-L86

While rollback of previously called interactors do not run with their dedicated callbacks.

https://github.com/aaronmallen/activeinteractor/blob/1f4afa8b7cc8fcfd890ef555622f6f2274eaa632/lib/active_interactor/context/status.rb#L81-L86

**Comment by aaronmallen** [comment]
@mohameddiaa27 do you think we can fix this in a backwards compatible manner?

**Comment by mohameddiaa27** [comment]
@aaronmallen Let me try it in a draft PR and check. Although the rollback flow may require further adjustments to merge contexts after rollback which addresses https://github.com/aaronmallen/activeinteractor/issues/210. But let us keep it simple for now and try this one
